
[font]
size = 14

[font.bold]
#family = "MesloLGS NF"
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
# family = "MesloLGS NF"
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
# family = "MesloLGS NF"
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.8

[general]
#import = ["~/.config/alacritty/dracula.toml"]
#import = ["~/.config/alacritty/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/catppuccin-macchiato.toml"]

[env]
TERM = "xterm-256color"
